ksk/pizza/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,TextAreaField
from flask_wtf.file import FileField,FileAllowed
from wtforms.validators import ValidationError,DataRequired,Length
from ksk.models import Pizza

class PizzaForm(FlaskForm):
    product_code = StringField('Product Code',validators=[DataRequired()])
    type = StringField('Type',validators=[DataRequired()])
    image_file = FileField('Upload An Image',validators=[FileAllowed(['jpg','jpeg'])])
    product_detail = TextAreaField('About Your Product',validators=[DataRequired(),Length(min=1,max=100)])
    submit = SubmitField('Upload')

    def validate_product_code(self,product_code):
        product = Pizza.query.filter_by(product_code=product_code.data).first()
        if product:
            raise ValidationError(f'This product code: {product_code.data} has already existed')
    
    def validate_type(self,type):
        product = Pizza.query.filter_by(type=type.data).first()
        if product:
            raise ValidationError(f'This product type: {type.data} has already existed')

ksk/breaksnack/routes.py
from flask import Blueprint,request,redirect,render_template,url_for,flash
from flask_login import login_required
from ksk.breaksnack.utils import save_img_for_breadsnack
from ksk import db
from ksk.models import BreadSnack
from ksk.breaksnack.forms import BreadSnackForm

breadsnacks = Blueprint('breadsnacks',__name__)

########## Bread & Muffin Upload ##########

@breadsnacks.route('/upload/bread&snack',methods=['GET','POST'])
@login_required
def upload_breadsnack():
    form = BreadSnackForm()
    if form.validate_on_submit():
        breadsnack = BreadSnack(form.product_code.data,form.type.data,form.product_detail.data)
        if form.image_file.data:
            product_img = save_img_for_breadsnack((form.image_file.data))
            breadsnack.image_file = product_img
        db.session.add(breadsnack)
        db.session.commit()
        flash('New Product has been uploaded!','info')
        return redirect(url_for('breadsnacks.view_breadsnack')) 

    return render_template('product_upload_form.html',category="Bread & Snacks",title="Bread & Muffin Upload",form=form)

########### Bread & Muffin View #################
@breadsnacks.route('/product/bread&snack')
def view_breadsnack():
    page = request.args.get('page',1,type=int)
    breadsnacks = BreadSnack.query.order_by(BreadSnack.date_posted.desc()).paginate(page=page,per_page=3)
    return render_template('breadsnack_view.html',title="Bread & Snack",breadsnacks=breadsnacks)

ksk/main/routes.py
from flask import Blueprint,render_template

main = Blueprint('main',__name__)

@main.route("/")
@main.route("/home")
def home():
    return render_template('home.html',title="Home Page")

ksk/pizza/routes.py
from flask import Blueprint,flash,url_for,redirect,render_template,request
from flask_login import login_required
from ksk.models import Pizza
from ksk import db
from ksk.pizza.utils import save_img_for_pizza
from ksk.pizza.forms import PizzaForm

pizzas = Blueprint('pizzas',__name__)

########## Pizza Upload #############
@pizzas.route('/upload/pizza',methods=['GET','POST'])
@login_required
def upload_pizza():
    form = PizzaForm()
    if form.validate_on_submit():
        pizza = Pizza(form.product_code.data,form.type.data,form.product_detail.data)
        if form.image_file.data:
            product_img = save_img_for_pizza((form.image_file.data))
            pizza.image_file = product_img
        db.session.add(pizza)
        db.session.commit()
        flash('New Product has been uploaded!','info')
        return redirect(url_for('pizzas.view_pizza')) 

    return render_template('product_upload_form.html',category="Pizza",title="Pizza Upload",form=form)

######### Pizza Client View #############
@pizzas.route('/product/pizza')
def view_pizza():
    page = request.args.get('page',1,type=int)
    pizzas = Pizza.query.order_by(Pizza.date_posted.desc()).paginate(page=page,per_page=3)
    return render_template('pizza_view.html',title="Pizza",pizzas=pizzas)

ksk/users/routes.py
from flask import Blueprint,flash,render_template,redirect,request,url_for,current_app
from flask_login import login_required,login_user,logout_user,current_user
from ksk.models import BreadSnack, Pizza, User
from ksk import bcrypt,db
from ksk.users.utils import send_mail,save_img_for_pizza,save_img_for_breadsnack
from ksk.users.forms import LoginForm,RequestResetForm,ResetPasswordForm,KSKPizzaUpdateForm,KSKBreadSnackUpdateForm
import os

users = Blueprint('users',__name__)

###### Admin Login #######
@users.route("/kskadmin",methods=['GET','POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,form.password.data):
            login_user(user)
            flash('You have successfully logged in')
            return redirect(url_for('users.admin_panel')) #need to modify later
        else:
            flash('Wrong Password or Email!','warning')
            return redirect(url_for('users.login'))
    return render_template('login.html',title="Login",form=form)

######## Admin Logout #########
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

########### Admin Panel ###############
@users.route('/admin_panel')
@login_required
def admin_panel():
    return render_template('admin_panel.html',title="Admin Panel")

############# Account ################
@users.route('/account')
@login_required
def account():
    return render_template('account.html')


############ Generate Token #############
@users.route('/reset_password',methods=['GET','POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('users.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_mail(user)
        flash('Reset Password Mail has been sent to your email account')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html',title='Reset Password',form=form)

############### Reset Password #############

@users.route('/reset_password/<token>',methods=['GET','POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('users.home'))
    user = User.validate_token(token)
    if user is None:
        flash('That is an invalid or expired token','warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated!')
        return redirect(url_for('users.login'))

    return render_template('reset_password.html',title='Reset Password',form=form)

######### Admin KSK Pizza Update and Delete ########
@users.route('/ksk_pizzas')
@login_required
def ksk_pizzas():
    page = request.args.get('page',1,type=int)
    pizzas = Pizza.query.order_by(Pizza.date_posted.desc()).paginate(page=page,per_page=3)
    return render_template('ksk_pizzas.html',title='KSK Products',pizzas=pizzas)

@users.route('/edit_pizzas/<int:pizza_id>')
@login_required
def edit_pizzas(pizza_id):
    pizza = Pizza.query.get(pizza_id)
    return render_template('edit_pizzas.html',title="Edit Pizza Products",pizza=pizza)

@users.route('/update_pizza/<int:pizza_id>',methods=['POST','GET'])
@login_required
def update_pizza(pizza_id):
    pizza = Pizza.query.get_or_404(pizza_id)
    form = KSKPizzaUpdateForm()
    if form.validate_on_submit():
        if form.image_file.data:
            product_img = save_img_for_pizza(form.image_file.data)
            pizza.image_file = product_img
        pizza.type = form.type.data
        pizza.product_detail = form.product_detail.data
        db.session.commit()
        flash('Your proudct has been updated!')
        return redirect(url_for('users.ksk_pizzas'))
    elif request.method == "GET":
        form.type.data = pizza.type
        form.product_detail.data = pizza.product_detail 
    return render_template('pizza_update_form.html',title="Update Pizza",form=form,pizza=pizza)

@users.route('/delete_pizza/<int:pizza_id>',methods=['POST'])
@login_required
def delete_pizza(pizza_id):
    pizza = Pizza.query.get_or_404(pizza_id)
    if pizza.image_file != "default.jpg":
        picture_to_delete = os.path.join(current_app.root_path,'static/product_images/pizza',pizza.image_file)
        os.remove(picture_to_delete)
    db.session.delete(pizza)
    db.session.commit()
    flash('Your product has been deleted!')
    return redirect(url_for('users.ksk_pizzas'))

######### Admin KSK Bread & Snack Update and Delete ########
@users.route('/ksk_breadsnacks')
@login_required
def ksk_breadsnacks():
    page = request.args.get('page',1,type=int)
    breadsnacks = BreadSnack.query.order_by(BreadSnack.date_posted.desc()).paginate(page=page,per_page=3)
    return render_template('ksk_breadsnacks.html',title='KSK Products',breadsnacks=breadsnacks)

@users.route('/edit_breadsnacks/<int:breadsnack_id>')
@login_required
def edit_breadsnacks(breadsnack_id):
    breadsnack = BreadSnack.query.get(breadsnack_id)
    return render_template('edit_breadsnacks.html',title="Edit Bread & Snack Products",breadsnack=breadsnack)

@users.route('/update_breadsnack/<int:breadsnack_id>',methods=['POST','GET'])
@login_required
def update_breadsnack(breadsnack_id):
    breadsnack = BreadSnack.query.get_or_404(breadsnack_id)
    form = KSKBreadSnackUpdateForm()
    if form.validate_on_submit():
        if form.image_file.data:
            product_img = save_img_for_breadsnack(form.image_file.data)
            breadsnack.image_file = product_img
        breadsnack.type = form.type.data
        breadsnack.product_detail = form.product_detail.data
        db.session.commit()
        flash('Your proudct has been updated!')
        return redirect(url_for('users.ksk_breadsnacks'))
    elif request.method == "GET":
        form.type.data = breadsnack.type
        form.product_detail.data = breadsnack.product_detail 
    return render_template('breadsnack_update_form.html',title="Update Bread & Snacks",form=form,breadsnack=breadsnack)

@users.route('/delete_breadsnack/<int:breadsnack_id>',methods=['POST'])
@login_required
def delete_breadsnack(breadsnack_id):
    breadsnack = BreadSnack.query.get_or_404(breadsnack_id)
    if breadsnack.image_file != "default.jpg":
        picture_to_delete = os.path.join(current_app.root_path,'static/product_images/breadsnack',breadsnack.image_file)
        os.remove(picture_to_delete)
    db.session.delete(breadsnack)
    db.session.commit()
    flash('Your product has been deleted!')
    return redirect(url_for('users.ksk_breadsnacks'))

ksk/templates/admin_panel.html
{% extends "base.html" %}

{% block content %}

{% for message in get_flashed_messages() %}
    <h3>{{ message }}</h3>
{% endfor %}

<div class="wrapper-grey padded">
        <div class="container">
            <h2 class="text-center">Upload Session</h2>
            <div class="col-xs-12 col-sm-4">
                <div class="card" style="background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2));">
                <div class="card-category">KSK</div>
                <img style="height: 248px; border-radius: 2%;"  src="{{ url_for('static',filename='images/card1.jpg') }}" alt="cakes" />
                <div class="card-description">
                    <h2>Cakes</h2>
                    <p>Different styles and flavours</p>
                </div>
                <img class="card-user avatar avatar-large" src="{{  url_for('static',filename='images/ksklogo.png') }}">
                <a class="card-link" href="https://www.google.com" ></a>
                </div>
                <a href="#" class="btn btn-primary" role="button">View Uploaded Cakes</a>
            </div>
            <div class="col-xs-12 col-sm-4">
                <div class="card" style="background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2));">
                <div class="card-category">KSK</div>
                <img style="height: 248px; border-radius: 2%;"  src="{{ url_for('static',filename='images/card2.jpg') }}" alt="breads&muffins" />
                <div class="card-description">
                    <h2>Breads and Muffins</h2>
                    <p>Big and Delicious</p>
                </div>
                <img class="card-user avatar avatar-large" src="{{  url_for('static',filename='images/ksklogo.png') }}">
                <a class="card-link" href="{{ url_for('breadsnacks.upload_breadsnack') }}" ></a>
                </div>
                <a href="{{ url_for('users.ksk_breadsnacks') }}" class="btn btn-primary" role="button">View Uploaded Bread & Snacks</a>
            </div>
            <div class="col-xs-12 col-sm-4">
                <div class="card" style="background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2));">
                <div class="card-category">KSK</div>
                <img style="height: 248px; border-radius: 2%;"  src="{{ url_for('static',filename='images/card3.jpg') }}" alt="pizza" />
                <div class="card-description">
                    <h2>Pizza</h2>
                    <p>Chessy and Yummy Slices</p>
                </div>
                <img class="card-user avatar avatar-large" src="{{  url_for('static',filename='images/ksklogo.png') }}">
                <a class="card-link" href="{{ url_for('pizzas.upload_pizza') }}" ></a>
                </div>
                <a href="{{ url_for('users.ksk_pizzas') }}" class="btn btn-primary" role="button">View Uploaded Pizzas</a>
            </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

ksk/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,700|Raleway:300,400,500,700">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{ url_for('static',filename='main.css') }}" />
    <title>{{ title }} - Kyal Sin Kha</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3">
            <div class="container">
                <a href="{{ url_for('main.home') }}" class="navbar-brand">KYAL SIN KHA</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navmenu">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navmenu">
                    <ul class="navbar-nav ms-auto">
                        {% if current_user.is_authenticated %}
                        <li class="nav-item">
                            <a href="#" class="nav-link">My Account</a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ url_for('users.admin_panel') }}" class="nav-link">Upload New Product</a>
                        </li>
                        <li class="nav-item">
                            <a href="{{ url_for('users.logout') }}" class="nav-link">Logout</a>
                        </li>
                        <li class="nav-item">
                            <a href="tel:09976397232" class="nav-link">Contact Kwee Zig</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a href="#category" class="nav-link">What We Offer</a>
                        </li>
                        <li class="nav-item">
                            <a href="#shopping" class="nav-link">Shop Now</a>
                        </li>
                        <li class="nav-item">
                            <a href="#contact" class="nav-link">Contact Us</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <article>
        {% block content %} {% endblock %}
    </article>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
        crossorigin="anonymous"></script>
    <!-- Including Bootstrap JS (with its jQuery dependency) so that dynamic components work -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>


</body>

</html>

ksk/templates/breadsnack_update_form.html
{% extends "base.html" %}

{% block content %}
<div class="registration-form">
        <form action="" method="POST" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
           <div class="category_img">
               <h1><center>Bread & Snack</center></h1>
           </div>
           <br/>
           <div>
               <h3>Product Code : {{ breadsnack.product_code }}</h3>
           </div>
            <div class="form-group">
                {{ form.type.label }}<br/>
                {{ form.type (class="form-control item") }}
            </div>
            {% if form.type.errors %}
                {% for error in form.type.errors %}
                    <div style="color: red;">{{ error }}</div>
                {% endfor %}
            {% endif %}
            <div class="form-group">
                {{ form.image_file.label }}<br/>
                {{ form.image_file (class="form-group item")}}
            </div>
            {% if form.image_file.errors %}
                {% for error in form.image_file.errors %}
                    <div style="color: red;">{{ error }}</div>
                {% endfor %}
            {% endif %}
            <div class="form-group">
                {{ form.product_detail.label }}<br/>
                {{ form.product_detail (class="form-label item") }}
            </div>
            <div class="form-group">
                {{ form.submit(class='btn btn-outline-info')}}
            </div>
        </form>
    </div>
{% endblock %}

ksk/templates/breadsnack_view.html
{% extends "base.html" %}

{% block content %}

{% for message in get_flashed_messages() %}
<h3>{{ message }}</h3>
{% endfor %}

{% for bs in breadsnacks.items %}

<div id="products" class="container">
    <div class="row row-cols-1 row-cols-md-2 g-4">
        <div class="col">
            <div class="card text-dark bg-warning" style="width: 30rem; height: 50rem;">
                <img style="width: 300px; height: 200px;"
                    src="{{ url_for('static',filename='product_images/breadsnack/'+ bs.image_file) }}"
                    class="card-img-top" alt="...">
                <div class="card-body">
                    <h1 class="card-title">{{ bs.type }}</h1>
                    <h3 class="card-text">Product Code: <b>{{ bs.product_code }}</b></h3>
                    <p class="card-text">{{ bs.product_detail }} </p>
                </div>
                <br />
                <a href="tel:09976397232" class="btn btn-primary">Order Now</a>
            </div>
            <br /><br /><br />
        </div>
    </div>
</div>

{% endfor %}


{% for page_num in breadsnacks.iter_pages() %}
{% if page_num %}
<a style="width: 100px;" class="btn btn-dark mb-4 btn-lg" href="{{ url_for('breadsnacks.view_breadsnack',page=page_num) }}">{{ page_num
    }}</a>
{% else %}
...
{% endif %}
{% endfor %}

{% endblock %}

ksk/templates/edit_breadsnacks.html
{% extends "base.html" %}

{% block content %}
<div id="products" class="container">
    <div class="row row-cols-1 row-cols-md-2 g-4">
        <div class="col">
            <div class="card text-dark bg-warning" style="width: 30rem; height: 50rem;">
                <img style="width: 300px; height: 200px;"
                    src="{{ url_for('static',filename='product_images/breadsnack/'+ breadsnack.image_file) }}"
                    class="card-img-top" alt="...">
                <div class="card-body">
                    <h1 class="card-title">{{ breadsnack.type }}</h1>
                    <!-- Update & Delete Button modal -->
                    <a href="{{ url_for('users.update_breadsnack',breadsnack_id=breadsnack.id) }}" class="btn btn-primary"
                        role="button">Update</a>
                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#DeleteModal">
                        Delete
                    </button>
                    <h3 class="card-text">Product Code: <b>{{ breadsnack.product_code }}</b></h3>
                    <p class="card-text">{{ breadsnack.product_detail }} </p>
                </div>
                <br />
                <a href="tel:09976397232" class="btn btn-primary">Order Now</a>
            </div>
            <br /><br /><br />
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="DeleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="DeleteModalLabel">Do you really want to delete the product?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                You product will be deleted permanently.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('users.delete_breadsnack',breadsnack_id=breadsnack.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
            </div>
        </div>
    </div>
</div>
{% endblock %}

ksk/templates/edit_pizzas.html
{% extends "base.html" %}

{% block content %}
<div id="products" class="container">
    <div class="row row-cols-1 row-cols-md-2 g-4">
        <div class="col">
            <div class="card text-dark bg-warning" style="width: 30rem; height: 50rem;">
                <img style="width: 300px; height: 200px;"
                    src="{{ url_for('static',filename='product_images/pizza/'+ pizza.image_file) }}"
                    class="card-img-top" alt="...">
                <div class="card-body">
                    <h1 class="card-title">{{ pizza.type }}</h1>
                    <!-- Update & Delete Button modal -->
                    <a href="{{ url_for('users.update_pizza',pizza_id=pizza.id) }}" class="btn btn-primary"
                        role="button">Update</a>
                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#DeleteModal">
                        Delete
                    </button>
                    <h3 class="card-text">Product Code: <b>{{ pizza.product_code }}</b></h3>
                    <p class="card-text">{{ pizza.product_detail }} </p>
                </div>
                <br />
                <a href="tel:09976397232" class="btn btn-primary">Order Now</a>
            </div>
            <br /><br /><br />
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="DeleteModal" tabindex="-1" role="dialog" aria-labelledby="DeleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="DeleteModalLabel">Do you really want to delete the product?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                You product will be deleted permanently.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{ url_for('users.delete_pizza',pizza_id=pizza.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
            </div>
        </div>
    </div>
</div>
{% endblock %}

ksk/templates/ksk_breadsnacks.html
{% extends "base.html" %}

{% block content %}

{% for message in get_flashed_messages() %}
<h3>{{ message }}</h3>
{% endfor %}

{% for breadsnack in breadsnacks.items %}

<div id="products" class="container">
    <div class="row row-cols-1 row-cols-md-2 g-4">
        <div class="col">
            <div class="card text-dark bg-warning" style="width: 30rem; height: 50rem;">
                <img style="width: 300px; height: 200px;" src="{{ url_for('static',filename='product_images/breadsnack/'+ breadsnack.image_file) }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <a href="{{ url_for('users.edit_breadsnacks',breadsnack_id=breadsnack.id) }}"><h1 class="card-title">{{ breadsnack.type }}</h1></a>
                    <h3 class="card-text">Product Code: <b>{{ breadsnack.product_code }}</b></h3>
                    <p class="card-text">{{ breadsnack.product_detail }} </p>
                </div>
                <br/>
                <a href="tel:09976397232" class="btn btn-primary">Order Now</a>
            </div>
            <br/><br/><br/>
        </div>
    </div>
</div>

{% endfor %}


{% for page_num in breadsnacks.iter_pages() %}
    {% if page_num %}
        <a style="width: 100px;" class="btn btn-dark mb-4 btn-lg" href="{{ url_for('users.ksk_breadsnacks',page=page_num) }}">{{ page_num }}</a>
    {% else %}
        ...
    {% endif %}
{% endfor %}

{% endblock %}

ksk/templates/login.html
{% extends "base.html" %}

{% block content %}

{% for message in get_flashed_messages() %}
    <h3>{{ message }}</h3>
{% endfor %}

{% if form %}
    <div class="login-dark">
        <form action="{{ url_for('users.login') }}" method="post">
            {{ form.hidden_tag() }}
            <h1>Login Form</h1>
            <div class="illustration"><i class="icon ion-ios-locked-outline"></i></div>
            <div  class="form-group">
                {{ form.email.label }}<br/>
                {{ form.email (class="form-control-lg") }}
            </div>
            {% if form.email.errors %}
                {% for error in form.email.errors %}
                    {{ error }}
                {% endfor %}
            {% endif %}
            <div class="form-group">
                {{ form.password.label }}<br/>
                {{ form.password (class="form-control-lg") }}
            </div>
            {% if form.password.errors %}
                {% for error in form.password.errors %}
                    {{ error }}
                {% endfor %}
            {% endif %}
            <div style="color: black;" class="form-group">{{ form.submit }}</div>
            <a href="{{ url_for('users.reset_request') }}" class="forgot">Forgot your email or password?</a></form>
    </div>
{% endif %}

{% endblock %}

ksk/templates/pizza_update_form.html
{% extends "base.html" %}

{% block content %}
<div class="registration-form">
        <form action="" method="POST" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
           <div class="category_img">
               <h1><center>Pizza</center></h1>
           </div>
           <br/>
           <div>
               <h3>Product Code : {{ pizza.product_code }}</h3>
           </div>
            <div class="form-group">
                {{ form.type.label }}<br/>
                {{ form.type (class="form-control item") }}
            </div>
            {% if form.type.errors %}
                {% for error in form.type.errors %}
                    <div style="color: red;">{{ error }}</div>
                {% endfor %}
            {% endif %}
            <div class="form-group">
                {{ form.image_file.label }}<br/>
                {{ form.image_file (class="form-group item")}}
            </div>
            {% if form.image_file.errors %}
                {% for error in form.image_file.errors %}
                    <div style="color: red;">{{ error }}</div>
                {% endfor %}
            {% endif %}
            <div class="form-group">
                {{ form.product_detail.label }}<br/>
                {{ form.product_detail (class="form-label item") }}
            </div>
            <div class="form-group">
                {{ form.submit(class='btn btn-outline-info')}}
            </div>
        </form>
    </div>
{% endblock %}

ksk/templates/pizza_view.html
{% extends "base.html" %}

{% block content %}

{% for message in get_flashed_messages() %}
<h3>{{ message }}</h3>
{% endfor %}

{% for pizza in pizzas.items %}

<div id="products" class="container">
    <div class="row row-cols-1 row-cols-md-2 g-4">
        <div class="col">
            <div class="card text-dark bg-warning" style="width: 30rem; height: 50rem;">
                <img style="width: 300px; height: 200px;" src="{{ url_for('static',filename='product_images/pizza/'+ pizza.image_file) }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h1 class="card-title">{{ pizza.type }}</h1>
                    <h3 class="card-text">Product Code: <b>{{ pizza.product_code }}</b></h3>
                    <p class="card-text">{{ pizza.product_detail }} </p>
                </div>
                <br/>
                <a href="tel:09976397232" class="btn btn-primary">Order Now</a>
            </div>
            <br/><br/><br/>
        </div>
    </div>
</div>

{% endfor %}


{% for page_num in pizzas.iter_pages() %}
    {% if page_num %}
        <a style="width: 100px;" class="btn btn-dark mb-4 btn-lg" href="{{ url_for('pizzas.view_pizza',page=page_num) }}">{{ page_num }}</a>
    {% else %}
        ...
    {% endif %}
{% endfor %}

{% endblock %}